global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'lab31-rate-limiter'
    static_configs:
      - targets: ['rate-limiter:8000']
    metrics_path: /metrics

  - job_name: 'lab31-sample-api-1'
    static_configs:
      - targets: ['sample-api-1:8000']
    metrics_path: /metrics

  - job_name: 'lab31-sample-api-2'
    static_configs:
      - targets: ['sample-api-2:8000']
    metrics_path: /metrics
