global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab52-otel-collector:8889']

  - job_name: 'frontend'
    static_configs:
      - targets: ['lab52-frontend:8000']
    metrics_path: /metrics

  - job_name: 'hedger'
    static_configs:
      - targets: ['lab52-hedger:8080']
    metrics_path: /metrics

  - job_name: 'backend-1'
    static_configs:
      - targets: ['lab52-backend-1:8001']
    metrics_path: /metrics

  - job_name: 'backend-2'
    static_configs:
      - targets: ['lab52-backend-2:8002']
    metrics_path: /metrics

  - job_name: 'backend-3'
    static_configs:
      - targets: ['lab52-backend-3:8003']
    metrics_path: /metrics
