global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'lab24-scheduler'
    static_configs:
      - targets: ['scheduler:8000']
    metrics_path: /metrics

  - job_name: 'lab24-worker-1'
    static_configs:
      - targets: ['worker-1:9100']

  - job_name: 'lab24-worker-2'
    static_configs:
      - targets: ['worker-2:9100']

  - job_name: 'lab24-worker-3'
    static_configs:
      - targets: ['worker-3:9100']
