global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'writer-service'
    static_configs:
      - targets: ['writer-service:8000']
    metrics_path: /metrics

  - job_name: 'cdc-consumer'
    static_configs:
      - targets: ['cdc-consumer:8001']
    metrics_path: /metrics

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:8002']
    metrics_path: /metrics

  - job_name: 'polling-service'
    static_configs:
      - targets: ['polling-service:8003']
    metrics_path: /metrics
