global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8000']
    metrics_path: /metrics

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8001']
    metrics_path: /metrics

  - job_name: 'consumer-2'
    static_configs:
      - targets: ['consumer-2:8001']
    metrics_path: /metrics

  - job_name: 'api'
    static_configs:
      - targets: ['api:8003']
    metrics_path: /metrics
