global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:8000']
    metrics_path: /metrics

  - job_name: 'api'
    static_configs:
      - targets: ['api:8001']
    metrics_path: /metrics

  - job_name: 'orders'
    static_configs:
      - targets: ['orders:8002']
    metrics_path: /metrics

  - job_name: 'inventory'
    static_configs:
      - targets: ['inventory:8003']
    metrics_path: /metrics
