global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'lab20-api-1'
    static_configs:
      - targets: ['api-1:8000']
    metrics_path: /metrics

  - job_name: 'lab20-api-2'
    static_configs:
      - targets: ['api-2:8000']
    metrics_path: /metrics

  - job_name: 'lab20-api-3'
    static_configs:
      - targets: ['api-3:8000']
    metrics_path: /metrics
