global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'ring-coordinator'
    static_configs:
      - targets: ['ring-coordinator:8080']
    metrics_path: /metrics

  - job_name: 'storage-node-1'
    static_configs:
      - targets: ['storage-node-1:8080']
    metrics_path: /metrics

  - job_name: 'storage-node-2'
    static_configs:
      - targets: ['storage-node-2:8080']
    metrics_path: /metrics

  - job_name: 'storage-node-3'
    static_configs:
      - targets: ['storage-node-3:8080']
    metrics_path: /metrics

  - job_name: 'storage-node-4'
    static_configs:
      - targets: ['storage-node-4:8080']
    metrics_path: /metrics

  - job_name: 'client'
    static_configs:
      - targets: ['client:8090']
    metrics_path: /metrics
