global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab39-otel-collector:8889']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['lab39-api-gateway:8000']
    metrics_path: /metrics

  - job_name: 'shard-0'
    static_configs:
      - targets: ['lab39-shard-0:9000']
    metrics_path: /metrics

  - job_name: 'shard-1'
    static_configs:
      - targets: ['lab39-shard-1:9001']
    metrics_path: /metrics

  - job_name: 'shard-2'
    static_configs:
      - targets: ['lab39-shard-2:9002']
    metrics_path: /metrics

  - job_name: 'shard-3'
    static_configs:
      - targets: ['lab39-shard-3:9003']
    metrics_path: /metrics
