global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab26-otel-collector:8889']

  - job_name: 'lab26-gateway'
    static_configs:
      - targets: ['lab26-gateway:8000']
    metrics_path: /metrics

  - job_name: 'lab26-backend'
    static_configs:
      - targets: ['lab26-backend:8001']
    metrics_path: /metrics
