global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab28-otel-collector:8889']

  - job_name: 'lab28-chaos-controller'
    static_configs:
      - targets: ['lab28-chaos-controller:8080']
    metrics_path: /metrics

  - job_name: 'lab28-gateway'
    static_configs:
      - targets: ['lab28-gateway:8000']
    metrics_path: /metrics

  - job_name: 'lab28-order-service'
    static_configs:
      - targets: ['lab28-order-service:8001']
    metrics_path: /metrics

  - job_name: 'lab28-inventory-service'
    static_configs:
      - targets: ['lab28-inventory-service:8002']
    metrics_path: /metrics

  - job_name: 'lab28-payment-service'
    static_configs:
      - targets: ['lab28-payment-service:8003']
    metrics_path: /metrics
