global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab48-otel-collector:8889']

  - job_name: 'coordinator'
    static_configs:
      - targets: ['lab48-coordinator:8100']
    metrics_path: /metrics

  - job_name: 'id-generator-1'
    static_configs:
      - targets: ['lab48-id-generator-1:8001']
    metrics_path: /metrics

  - job_name: 'id-generator-2'
    static_configs:
      - targets: ['lab48-id-generator-2:8002']
    metrics_path: /metrics

  - job_name: 'id-generator-3'
    static_configs:
      - targets: ['lab48-id-generator-3:8003']
    metrics_path: /metrics

  - job_name: 'client'
    static_configs:
      - targets: ['lab48-client:8000']
    metrics_path: /metrics
