global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab46-otel-collector:8889']

  - job_name: 'coordinator'
    static_configs:
      - targets: ['lab46-coordinator:8000']
    metrics_path: /metrics

  - job_name: 'replica-1'
    static_configs:
      - targets: ['lab46-replica-1:9001']
    metrics_path: /metrics

  - job_name: 'replica-2'
    static_configs:
      - targets: ['lab46-replica-2:9002']
    metrics_path: /metrics

  - job_name: 'replica-3'
    static_configs:
      - targets: ['lab46-replica-3:9003']
    metrics_path: /metrics

  - job_name: 'replica-4'
    static_configs:
      - targets: ['lab46-replica-4:9004']
    metrics_path: /metrics

  - job_name: 'replica-5'
    static_configs:
      - targets: ['lab46-replica-5:9005']
    metrics_path: /metrics

  - job_name: 'client'
    static_configs:
      - targets: ['lab46-client:8080']
    metrics_path: /metrics
