global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab17-otel-collector:8889']

  - job_name: 'lab17-producer'
    static_configs:
      - targets: ['lab17-producer:8000']
    metrics_path: /metrics

  - job_name: 'lab17-worker'
    static_configs:
      - targets: ['lab17-worker:8001']
    metrics_path: /metrics

  - job_name: 'lab17-dlq-consumer'
    static_configs:
      - targets: ['lab17-dlq-consumer:8002']
    metrics_path: /metrics
