global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'api-warm'
    static_configs:
      - targets: ['api-warm:8000']
    metrics_path: /metrics

  - job_name: 'api-cold'
    static_configs:
      - targets: ['api-cold:8000']
    metrics_path: /metrics

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: /metrics

  - job_name: 'warmup-service'
    static_configs:
      - targets: ['warmup-service:8003']
    metrics_path: /metrics
