global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab30-otel-collector:8889']

  - job_name: 'lab30-client-gateway'
    static_configs:
      - targets: ['lab30-client-gateway:8000']
    metrics_path: /metrics

  - job_name: 'lab30-primary-db'
    static_configs:
      - targets: ['lab30-primary-db:8001']
    metrics_path: /metrics

  - job_name: 'lab30-replica-1'
    static_configs:
      - targets: ['lab30-replica-1:8002']
    metrics_path: /metrics

  - job_name: 'lab30-replica-2'
    static_configs:
      - targets: ['lab30-replica-2:8003']
    metrics_path: /metrics

  - job_name: 'lab30-failover-controller'
    static_configs:
      - targets: ['lab30-failover-controller:8010']
    metrics_path: /metrics
