global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab35-otel-collector:8889']

  - job_name: 'lab35-api-service'
    static_configs:
      - targets: ['lab35-api-service:8000']
    metrics_path: /metrics

  - job_name: 'lab35-worker-service'
    static_configs:
      - targets: ['lab35-worker-service:8001']
    metrics_path: /metrics
