global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab19-otel-collector:8889']

  - job_name: 'app-v1'
    static_configs:
      - targets: ['lab19-app-v1:8080']
    metrics_path: /metrics

  - job_name: 'app-v2'
    static_configs:
      - targets: ['lab19-app-v2:8080']
    metrics_path: /metrics

  - job_name: 'canary-controller'
    static_configs:
      - targets: ['lab19-canary-controller:8090']
    metrics_path: /metrics
