global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: /metrics

  - job_name: 'backend-fast'
    static_configs:
      - targets: ['backend-fast:8001']
    metrics_path: /metrics

  - job_name: 'backend-slow'
    static_configs:
      - targets: ['backend-slow:8002']
    metrics_path: /metrics

  - job_name: 'backend-flaky'
    static_configs:
      - targets: ['backend-flaky:8003']
    metrics_path: /metrics

  - job_name: 'client'
    static_configs:
      - targets: ['client:8080']
    metrics_path: /metrics
