global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'replica-1'
    static_configs:
      - targets: ['replica-1:8001']
    metrics_path: /metrics

  - job_name: 'replica-2'
    static_configs:
      - targets: ['replica-2:8002']
    metrics_path: /metrics

  - job_name: 'replica-3'
    static_configs:
      - targets: ['replica-3:8003']
    metrics_path: /metrics

  - job_name: 'sync-service'
    static_configs:
      - targets: ['sync-service:8010']
    metrics_path: /metrics

  - job_name: 'client'
    static_configs:
      - targets: ['client:8020']
    metrics_path: /metrics
