global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']
    metrics_path: /metrics

  - job_name: 'service-a'
    static_configs:
      - targets: ['service-a:8001']
    metrics_path: /metrics

  - job_name: 'service-b'
    static_configs:
      - targets: ['service-b:8002']
    metrics_path: /metrics
