global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab14-otel-collector:8889']

  - job_name: 'primary'
    static_configs:
      - targets: ['lab14-primary:8000']
    metrics_path: /metrics

  - job_name: 'replica1'
    static_configs:
      - targets: ['lab14-replica1:8001']
    metrics_path: /metrics

  - job_name: 'replica2'
    static_configs:
      - targets: ['lab14-replica2:8002']
    metrics_path: /metrics

  - job_name: 'client'
    static_configs:
      - targets: ['lab14-client:8003']
    metrics_path: /metrics
