global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['lab25-otel-collector:8889']

  - job_name: 'lab25-kv-store-wal'
    static_configs:
      - targets: ['lab25-kv-store-wal:8000']
    metrics_path: /metrics

  - job_name: 'lab25-kv-store-nowal'
    static_configs:
      - targets: ['lab25-kv-store-nowal:8000']
    metrics_path: /metrics
