global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "model-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["model-api:8000"]
        labels:
          service: "model-api"
